#' Plot Gubbin Tree
#' 
#' This function generates Gubbin Tree plot. 
#'
#' @param gubbin_tree tree file generated by Gubbins 
#' @param bactdate_tree tree file generated from bactdating
#' @param coltime_range range of collection time
#' @param divtime_range range of divergence time
#' @param distance_range range of the distance
#' @return plot of Gubbin tree
#' @export
plt_gubbin_tree = function(gubbin_tree){
  plt_tree = plot(gpsc8_tree, "c",FALSE, cex=0.6, no.margin = TRUE)
  return(plt_tree)
}

#' Match Tree Label to Metadata Label
#' 
#' This function generates pairwise matrices from metadata file. 
#'
#' @param Metadata metadata file 
#' @param Tree tree file generated from Gubbins
#' @param drop_tip_name the name of the tip to be dropped, usually the reference name
#' @param drop_tip TRUE to drop the tip of drop_tip_name
#' @return list of tree name
#' @export
match_tree_meta = function(Metadata, Tree, drop_tip_name, drop_tip = TRUE){
  if (drop_tip){
    ## drop reference tip from Gubbin tree
    tree_dropRef = drop.tip(Tree,drop_tip_name)
    ## create vector of tip labels
    id_order = tree_dropRef$tip.label
  } else{
    tree_dropRef = Tree
    id_order = Tree$tip.label
  }
  ## reorder tree based on order of tip labels (the order of the tip label should be the same in the lane_id)
  match_order = Metadata %>%
    dplyr::slice(match(id_order,lane_id))
  
  res_list = list("tree" = tree_dropRef, "match_tree_meta" = match_order)
  return(res_list)
}

#' Divergence time estimated by Bactdating
#' 
#' This function generates estimated divergence time between isolates
#'
#' @param match_tree_meta metadata file of combining tree file and metafile
#' @param dropRef_tree tree file generated from Gubbins without reference tip
#' @param save_bd_path path to save bactdating results
#' @param time use "Year_Collection" by default
#' @return roottotip and bactdating results
#' @export
time_resolved = function(match_tree_meta, dropRef_tree, save_bd_path, time="Year_collection"){
  collectionTime = as.numeric(match_tree_meta$time)
  rtd = roottotip(dropRef_tree, collectionTime)
  bd = bactdate(unroot(dropRef_tree), collectionTime, showProgress = T) ## MCMC process
  saveRDS(bd, save_bd_path)
  
  res_list = list("Root2Tip" = rtd, "BactDating" = bd)
  return(res_list)
}
